services:

  ### database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  ### native
#  native-api:
#    build:
#      context: .
#      dockerfile: native.Dockerfile
#    restart: no
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
#      DB_NAME: ${DB_NAME}
#      SERVER_PORT: 8080
#      JWT_SECRET: ${JWT_SECRET}
#      JWT_TTL: ${JWT_TTL}

  ### jvm
  jvm-api:
    build:
      context: .
      dockerfile: jvm.Dockerfile
    restart: unless-stopped
    ports:
      - "18080:18080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
      SERVER_PORT: 18080
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      APP_NAME: ${APP_NAME}
