### sign up
POST {{host}}/auth/signup
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}

### login
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}

### /category/list
GET {{host}}/category/list
Authorization: Bearer {{token}}

### /category/name/test
GET {{host}}/category/name/test
Authorization: Bearer {{token}}

### /product/list
GET {{host}}/product/list?page=0&size=1&sort=namn,asc
Authorization: Bearer {{token}}

### /product/1
GET {{host}}/product/1
Authorization: Bearer {{token}}
