name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build-docker-images:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/master' # Run on push to any branch except master

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker JVM Image
        run: docker build --file ./jvm.Dockerfile .

      - name: Build Docker Native Image
        run: docker build --file ./native.Dockerfile .

  build-and-push-docker-images:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Run on push to master branch

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Native Image
        run: |
          docker build --file ./native.Dockerfile . --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
